POST http://localhost:42069/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3NDQ0MDA1LCJ1c2VySWQiOjJ9.un4mH5QR5-mYvB9_VkeiBUzJrG-fftWVwpOLuKEFka8

{
    "name": "Test Event",
    "description": "A test Event",
    "location": "A test location",
    "dateTime": "{{$datetime iso8601}}"
}