POST http://localhost:42069/login
Content-Type: application/json

{
    "email": "test2@example.com",
    "password": "password"
}

# {
#     "email": "test1@example.com",
#     "password": "password234"
# }